# Generated by Django 2.1.8 on 2020-03-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Of Birth'),
        ),
    ]
