# Generated by Django 2.1.8 on 2020-03-24 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0002_customerprofile_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='pass_pin',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='company',
        ),
    ]
