# Generated by Django 2.1.8 on 2020-03-26 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0005_customerprofile_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='username',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='allow_mail',
            field=models.BooleanField(default=0, verbose_name='Allow Mail'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='birth_year',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Birth Year'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='facebook_id'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='job',
            field=models.BooleanField(default=0, verbose_name='job'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='last_logined',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Logind'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='married',
            field=models.BooleanField(default=0, verbose_name='married'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='nickname',
            field=models.CharField(default=1, max_length=100, unique=True, verbose_name='Nick Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='twitter_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='twitter_id'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('1', 'Admin'), ('0', 'Normal User')], max_length=100, null=True, verbose_name='User Type'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='company',
            field=models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CustomerProfile_Company', to='Brands.Company', verbose_name='Company'),
        ),
    ]
