# Generated by Django 2.1.8 on 2020-03-26 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0006_auto_20200326_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='User Name'),
        ),
    ]
