# Generated by Django 2.1.8 on 2020-03-26 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0008_auto_20200326_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='user_type',
            field=models.BooleanField(default=1, verbose_name='User Type'),
        ),
    ]
