# Generated by Django 2.1.8 on 2020-03-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0009_auto_20200326_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='prefecture',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Prefecture'),
        ),
    ]
