# Generated by Django 2.1.8 on 2020-03-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0010_customerprofile_prefecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='job',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='nickname',
            field=models.CharField(max_length=100, verbose_name='Nick Name'),
        ),
    ]
