# Generated by Django 2.1.8 on 2020-03-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0011_auto_20200326_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Password'),
        ),
    ]
