# Generated by Django 2.1.8 on 2020-03-26 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0013_auto_20200326_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='password',
        ),
    ]
