# Generated by Django 2.1.8 on 2020-03-26 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0014_remove_customerprofile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='auth_user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='CustomerProfile_auth_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
