# Generated by Django 2.1.8 on 2020-04-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0016_auto_20200326_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Password'),
        ),
    ]
