# Generated by Django 2.1.8 on 2020-04-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0017_customerprofile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nick Name'),
        ),
    ]
