# Generated by Django 2.1.8 on 2020-03-28 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstAreas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oversea', models.PositiveIntegerField(blank=True, null=True, verbose_name='Oversea')),
                ('area_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Area Name')),
                ('sort', models.PositiveIntegerField(blank=True, null=True, verbose_name='Sort')),
                ('draft', models.PositiveIntegerField(blank=True, null=True, verbose_name='Draft')),
                ('revision', models.PositiveIntegerField(blank=True, null=True, verbose_name='Revision')),
                ('area_code', models.PositiveIntegerField(blank=True, null=True, verbose_name='Area Code')),
                ('status', models.BooleanField(default=0, verbose_name='Is Active')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('modified', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
                ('deleted', models.DateTimeField(blank=True, null=True, verbose_name='Deleted')),
                ('company', models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Areas_Company', to='Brands.Company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Master Area',
                'verbose_name_plural': ' Master Areas',
            },
        ),
        migrations.CreateModel(
            name='MstSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oversea', models.PositiveIntegerField(blank=True, null=True, verbose_name='Oversea')),
                ('series_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Series Name')),
                ('sort', models.PositiveIntegerField(blank=True, null=True, verbose_name='Sort')),
                ('draft', models.PositiveIntegerField(blank=True, null=True, verbose_name='Draft')),
                ('revision', models.PositiveIntegerField(blank=True, null=True, verbose_name='Revision')),
                ('series_code', models.PositiveIntegerField(blank=True, null=True, verbose_name='Series Code')),
                ('status', models.BooleanField(default=0, verbose_name='Is Active')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('modified', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
                ('deleted', models.DateTimeField(blank=True, null=True, verbose_name='Deleted')),
                ('company', models.ForeignKey(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MstSeries_Company', to='Brands.Company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Master Series',
                'verbose_name_plural': ' Master Series',
            },
        ),
    ]
