# Generated by Django 2.1.8 on 2020-03-28 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_mstbooks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mstareas',
            name='company',
        ),
        migrations.RemoveField(
            model_name='mstseries',
            name='company',
        ),
    ]
