# Generated by Django 2.1.8 on 2020-03-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0003_auto_20200328_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstareas',
            name='oversea',
            field=models.BooleanField(blank=True, null=True, verbose_name='Oversea'),
        ),
    ]
