# Generated by Django 2.1.8 on 2020-03-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0004_auto_20200328_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstareas',
            name='draft',
            field=models.CharField(blank=True, choices=[('0', 'Unpublished'), ('1', 'While editing'), ('2', 'Release')], max_length=100, null=True, verbose_name='Draft'),
        ),
        migrations.AlterField(
            model_name='mstareas',
            name='oversea',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='Oversea'),
        ),
        migrations.AlterField(
            model_name='mstbooks',
            name='draft',
            field=models.CharField(blank=True, choices=[('0', 'Unpublished'), ('1', 'While editing'), ('2', 'Release')], max_length=100, null=True, verbose_name='Draft'),
        ),
        migrations.AlterField(
            model_name='mstseries',
            name='draft',
            field=models.CharField(blank=True, choices=[('0', 'Unpublished'), ('1', 'While editing'), ('2', 'Release')], max_length=100, null=True, verbose_name='Draft'),
        ),
    ]
