# Generated by Django 2.1.8 on 2020-03-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0005_auto_20200328_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstbooks',
            name='dl_map_enabled',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='dl_map_enabled'),
        ),
        migrations.AlterField(
            model_name='mstbooks',
            name='map_enabled',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='map_enabled'),
        ),
        migrations.AlterField(
            model_name='mstbooks',
            name='oversea',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='Oversea'),
        ),
        migrations.AlterField(
            model_name='mstbooks',
            name='paper_enabled',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='paper_enabled'),
        ),
        migrations.AlterField(
            model_name='mstbooks',
            name='station_enabled',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='Station Enabled'),
        ),
        migrations.AlterField(
            model_name='mstseries',
            name='oversea',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='Oversea'),
        ),
    ]
