# Generated by Django 2.1.8 on 2020-03-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0006_auto_20200329_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstbooks',
            name='book_type',
            field=models.CharField(blank=True, choices=[('0', 'QR book / Sales book'), ('1', 'QR book'), ('2', 'Sales book'), ('3', 'Free book'), ('4', 'QR books'), ('5', 'Free URL book')], max_length=100, null=True, verbose_name='Draft'),
        ),
    ]
