# Generated by Django 2.1.8 on 2020-03-30 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0009_auto_20200329_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstareas',
            name='draft',
            field=models.CharField(blank=True, choices=[('0', 'Unpublished'), ('1', 'Editing'), ('2', 'Release')], max_length=100, null=True, verbose_name='Draft'),
        ),
        migrations.AlterField(
            model_name='mstseries',
            name='series_code',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Series Code'),
        ),
    ]
