# Generated by Django 2.1.8 on 2020-03-31 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0010_auto_20200330_0512'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstBookTourareas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
                ('modified', models.DateTimeField(blank=True, null=True, verbose_name='Updation Date & Time')),
                ('deleted', models.DateTimeField(blank=True, null=True, verbose_name='Deleted')),
                ('draft', models.CharField(blank=True, choices=[('0', 'Unpublished'), ('1', 'While editing'), ('2', 'Release')], max_length=100, null=True, verbose_name='Draft')),
                ('revision', models.PositiveIntegerField(blank=True, null=True, verbose_name='Revision')),
                ('tt_id', models.CharField(db_column='TT_ID', max_length=10)),
            ],
            options={
                'verbose_name': 'Master Books Tourareas',
                'verbose_name_plural': 'Master Books Tourareas',
                'db_table': 'mst_book_tourareas',
            },
        ),
        migrations.AlterField(
            model_name='mstareas',
            name='oversea',
            field=models.BooleanField(blank=True, choices=[('1', 'overseas'), ('0', 'domestic')], null=True, verbose_name='Oversea'),
        ),
        migrations.AlterField(
            model_name='mstbooks',
            name='oversea',
            field=models.BooleanField(blank=True, choices=[('1', 'overseas'), ('0', 'domestic')], null=True, verbose_name='Oversea'),
        ),
        migrations.AlterField(
            model_name='mstseries',
            name='oversea',
            field=models.BooleanField(blank=True, choices=[('1', 'overseas'), ('0', 'domestic')], null=True, verbose_name='Oversea'),
        ),
        migrations.AddField(
            model_name='mstbooktourareas',
            name='isbn_edition',
            field=models.ForeignKey(db_column='isbn_edition', on_delete=django.db.models.deletion.DO_NOTHING, to='Book.MstBooks'),
        ),
    ]
