# Generated by Django 2.1.8 on 2020-04-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0013_auto_20200406_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='mstbooks',
            name='download_url',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Download Url'),
        ),
        migrations.AddField(
            model_name='mstbooks',
            name='thumbnailURL',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Thumbnail Url'),
        ),
    ]
