# Generated by Django 2.1.8 on 2020-04-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0015_auto_20200410_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstbooks',
            name='epub',
            field=models.FileField(blank=True, null=True, upload_to='epub', verbose_name='Epub'),
        ),
    ]
