# Generated by Django 2.1.8 on 2020-04-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0016_auto_20200410_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstbooks',
            name='epub_cover',
            field=models.FileField(blank=True, null=True, upload_to='epub', verbose_name='Epub Cover'),
        ),
    ]
