# Generated by Django 2.1.8 on 2020-04-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0017_auto_20200410_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstbooks',
            name='epub_cover',
            field=models.FileField(blank=True, null=True, upload_to='epubcover', verbose_name='Epub Cover'),
        ),
    ]
