# Generated by Django 2.1.8 on 2020-04-13 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0018_auto_20200410_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mstbooks',
            name='download_url',
        ),
        migrations.RemoveField(
            model_name='mstbooks',
            name='thumbnailURL',
        ),
    ]
